compiler_stmt.go

Currently, `goja` panics when trying to compile a `debugger` statement.  According to the [spec](http://www.ecma-international.org/ecma-262/6.0/#sec-debugger-statement), a `debugger` statement is a no-op if no debugging facilities are present.  This PR adds an empty `case` statement for `*ast.DebuggerStatement` in `compiler.compileStatement` so that `debugger` statements become no-ops rather than causing the compiler to panic.
Fixes #3

Add DebuggerStatement to compiler.compileStatement

---

compiler.go
compiler_expr.go

In some cases `compiler.evalVM` will not be used at all, thus it's initialization may be postponed.
Benchmarks (equal results omitted):
```
benchmark                   old ns/op      new ns/op      delta
BenchmarkCompile-8          2732180        2518783        -7.81%
BenchmarkGoReflectGet-8     2461           2444           -0.69%
BenchmarkPut-8              47.7           48.1           +0.84%
BenchmarkPutStr-8           42.1           42.5           +0.95%
BenchmarkGet-8              14.5           14.2           -2.07%
BenchmarkArrayGetStr-8      23.0           23.8           +3.48%
BenchmarkArrayGet-8         63.0           62.5           -0.79%
BenchmarkArrayPut-8         17.1           17.2           +0.58%
BenchmarkToUTF8String-8     2.87           2.89           +0.70% …
```

compiler: create eval vm lazily

---

README.md

The example in the readme reaches `panic(num)` because it's trying to compare an `int64` with the default constant type `int`.
Also the call to `New` should use the package name.

Example in readme panics.

---

runtime.go
runtime_test.go

This pull request adds missing ToValue conversions for float32 and float64. They were showing up as objects in JavaScript instead of numbers, causing `===` and `Array.indexOf` to fail in my project.

Fixed conversion of Go float to Value

---

srcfile.go
srcfile_test.go

When `SrcFile.Position()` is called more than once for an offset in the last line of the file, the function panics because the index returned from `SearchInts()` is equal to `len(f.lineOffsets)`:
```
// SearchInts searches for x in a sorted slice of ints and returns the index
// as specified by Search. The return value is the index to insert x if x is
// not present (it could be len(a)).
// The slice must be sorted in ascending order.
//
func SearchInts(a []int, x int) int {
return Search(len(a), func(i int) bool { return a[i] >= x })
} 
```

Fixed index out of range panic in SrcFile.Position()

---

ast/node.go
compiler.go
parser/statement.go
runtime.go
srcfile.go
srcfile_test.go

Support to read internal and external (but local) sourcemaps. Remote sourcemaps based on http/https schemes are ignored on purpose.
Errors / exception lines and columns are mapped via the loaded sourcemap and represent the real error location. This is specifically useful when running transpiled (e.g. Typescript) code.

Support for sourcemaps

---

runtime.go
runtime_test.go

Runtime.ExportTo() couldn't handle structs which contain anonymous structs and/or pointer types.

Improved Runtime.ExportTo() to support anonymous structs and pointer types

---

runtime.go
runtime_test.go

These changes allow you to export a JavaScript date string into a time.Time target.
The following example shows why this behaviour would be nice to have:
```go
type Model struct {
ID        uint64
CreatedAt time.Time
}
test := &Model{
ID:        1,
CreatedAt: time.Now(),
}
bytes, _ := json.Marshal(test)
vm := New()
vm.RunString(fmt.Sprintf("var test = JSON.parse( '%s' )", bytes))
test2 := Model{}
err := vm.ExportTo(vm.Get("test"), &test2)
if err != nil {
t.Fatal(err)
}
if test.CreatedAt.Unix() != test2.CreatedAt.Unix() {
t.Fatalf("Unexpected value: '%v'", test2.CreatedAt)
}
```
Feel free to close this pull request if you disagree with the changes.

Runtime.ExportTo() can now export date strings to time.Time targets

---

builtin_date.go
runtime.go

For deterministic results, I need to control access to the current time.
There is already a way to control access to the random source via `Runtime.SetRandSource()`. This PR adds `Runtime.SetCurrentTimeGetter()` that works similarly.

Allow overriding the current time

---

runtime.go
runtime_test.go

Add a couple convenience functions for client code to easily handle `NaN` and `Inf` objects.

Add IsNaN and IsInfinity utility functions

---

value.go

Instead of adopting the #100 approach, add a `ClassName` function to `Object`.

Make class name a public field of Object

---

object_goreflect.go
object_goslice_reflect.go
object_goslice_reflect_test.go

In this merge request added push feature to slice. This is useful for interoperation between  go and js data structures.
In general it means, that this code should work with this MR as expected:
```
type Exported struct {
A []int
}
myExported := &Exported{}
vm.Set ("exported",&myExported)
vm.RunString (`exported.A.push(10)`)
// Here myExported.A array should contain element with value 10, which has been pushed from JS
```

Push support for goslice_reflect object

---

object_goreflect_test.go
runtime.go

This PR address issue with setting js Object to go struct. Current implementation of  toReflectValue just ignores `SetFieldNameMapper`. Here is fix of this.

[fix] toReflectValue use fieldNameMapper

---

builtin_json.go
builtin_json_test.go

Previous to this fix it was panicking on line 156.
And while fixing it I found that we are not calling it with the right name if it isn't an array. 
The test is the bare minimum, and this has a better fix in es6 branch as there there is already a Value with the item's name ;)

fix JSON.parse with reviver

---

parser/expression.go
parser/lexer.go
parser/parser_test.go
token/token.go
token/token_const.go

This actually lead to panics as the parser parsed it but then on
compliation it wasn't supported, but I can't find any reference to those
operators apart from otto so they seem to have never existed.

Drop &^ and &^= parsing as AND NOT operator doesn't exist

---

regexp.go
regexp_test.go

This was causing panics with ... such strange regex expressions

Correctly handle -1 submatch indexes from stdlib regexp

---

.tc39_test262_checkout.sh
.travis.yml

This is a slightly changed version from what was added in https://github.com/loadimpact/k6/pull/1747 to k6. 
I can if desired backport more of the changes including:
- running more of the test and saving how they fail and then compare that the failures don't change or disappear 
- some more filtering, probably not very useful without the above

Run the tc39/test262 in travic CI

---

object_test.go
parser/expression.go
tc39_test.go

Problems with this PR:
- I am not certain this shouldn't have more support in the lexer as currently, the lexer is breaking the tests about method/property names being able to be reserved words as long as they are escaped. My attempt at fixing it ... broke other stuff, and ultimately I think there is just not enough context in the lexer to know that it shouldn't allow it, which means that it should allow most reserved words, and then it needs to be checked later that it is actually not allowed. It seems like there is some such logic (which I broke with my previously mentioned "fix"), but ultimately I think this is not a very important issue and ultimately decided to give up on it.
- computed properties are used a lot throughout tests, and I meant to work on them as well, but the issue …

Add support for shorthand properties

---

builtin_proxy_test.go
proxy.go

Fix Proxy creation panicing on target not callable

---

string_ascii.go
string_test.go

With this simplified code it skips some allocations of byte slices
```
benchstat old.bench new.bench
name           old time/op    new time/op    delta
ASCIIConcat-8    44.3µs ± 5%    40.2µs ±12%   -9.18%  (p=0.000 n=10+10)
name           old alloc/op   new alloc/op   delta
ASCIIConcat-8    14.0kB ± 0%     9.9kB ± 0%  -29.28%  (p=0.000 n=10+10)
name           old allocs/op  new allocs/op  delta
ASCIIConcat-8       131 ± 0%       121 ± 0%   -7.63%  (p=0.000 n=10+10)
```

Simplify ascii string concat and skip some allocations

---

runtime.go

When working around the absence of contexts (#243), I noticed that when supply an error to the vm.Interrupt operation, the Golang conventions around error wrapping weren't working, and I couldn't unpick the root type error. 
This PR adds two helper wrapper methods so that when you call interrupt with a Go error, the underlying error returned from the runtime allows people to determine the root Go error involved. This allows you do things like:
```
_, err := vm.Interrupt(io.EOF)
....
require.ErrorIs(t, err, io.EOF, "Should contain io.EOF somewhere in the unwrap chain")
```

Error wrapping support for interrupts

---

runtime.go
runtime_test.go
vm.go

Previous to this the interrupt would be cleared whenever it is noticed
before it starts returning the error up the stack.
Unfortunately if you have goja code that called go code that called a
goja code and it got interrupted. Once we get back in the go code we
just got an error, and it's very likely that the code will just return it
so it's just an exception.
So at that point if there is `try/catch` it will just catch this and the
code will not actually be interrupted.
It is possible to at each such occurrence test that the error is not
InterruptError and Interrupt again, but that seems like the worse of two
choices.
So instead now the Interrupt will *not* be cleared and if the go code
just propagates the error - it will just keep interrupting.
But it is still possible to check the error …

Don't clear interrupt until the stack is empty

---

string_imported.go
string_test.go

This for example was completely breaking .length() on unicode strings

Build correct base object from importedString

---

builtin_function_test.go
parser/lexer.go
parser/lexer_test.go
tc39_test.go

Small modification for the lexer that enables skipping of the initial hashbang in the contents of a JavaScript script.
Tests with the `hashbang` feature in Test262 have therefore been enabled; except one (`function-constructor.js`) which makes use of `async`. To make up for this, I've added the `TestHashbangInFunctionConstructor` test written in Go.

Skip hashbang at beginning of source contents

---

file/file.go
file/file_test.go

Added trimming of whitespace from sourcemap source to avoid URL parse failures and nil pointer check to avoid nil pointer dereference

Fix nil pointer dereference panic when parsing sourcemaps sources with whitespaces

---

README.md

I found the examples helpful and thought it might make sense to add some consistency: 
1. When comparing the 2 different ways of working with functions, the one example used a SCRIPT variable while the other one didn't. This made it harder to spot the difference in the approaches. 
2. The first example used the `goja` package on the constructor while the subsequent examples didn't

More consistent examples in readme

---

builtin_json.go
builtin_json_test.go

Wrap the `io.EOF` in `JSON.parse` to make it human-oriented.
Resolves: #503

Make EOF in JSON.parse human-oriented.

---

builtin_string.go
string_ascii.go
tc39_test.go

Skip the https://github.com/tc39/test262/blob/main/test/built-ins/String/prototype/replaceAll/searchValue-replacer-RegExp-call.js due to regexp named groups.

Implement String.prototype.replaceAll

---

object_goreflect.go
object_goreflect_test.go

This is a small change to allow accessing the public fields of unexported embedded struct. For example:
```go
type base struct {
Name string
}
type Foo struct {
base
}
vm := goja.New()
vm.Set("foo", Foo{base{Name: "test"}})
vm.RunString("foo.Name") // currently prints undefined, expected "test"
```

Allow access to the public fields of unexported embedded struct

---

builtin_regexp.go
go.mod
go.sum
parser/regexp.go
parser/regexp_test.go
regexp.go
regexp_test.go
tc39_test.go

related: https://github.com/dop251/goja/issues/591
When the `DotAll` flag is passed, fallback directly to `regexp2`.

feat: regular expressions support DotAll flag

---

builtin_array.go
builtin_arrray_test.go
builtin_typedarrays.go
tc39_test.go

`{Array, TypedArray}.prototype.toSorted`
`{Array, TypedArray}.prototype.toReversed`
`{Array, TypedArray}.prototype.with`
`Array.prototype.toSpliced`

Implemented {Array, TypedArray}.prototype.{with, toReversed, toSorted}

---

builtin_promise.go
runtime_test.go

This is so that it can be handled at all.
Previously the error was just not propagated which lead to interrupts not really working with asynchronous code.
Fixes #623

Promise resolve and reject now return Interrupt errors

---

README.md

Brings more context about the implementation of setTimeout/setInterval - and why a JS engine cannot provide their implementation.

Update README.md - setTimeout()/setInterval()

---

runtime.go
runtime_test.go

See https://github.com/dop251/goja/discussions/653#discussioncomment-11952311.
I'm not sure if there should be more to go along with this, this bare minimum function makes sense in the above Proxy example, but if you're actually setting it to a new object rather than Proxying the old global, all the built-ins will be missing from the global scope. Maybe that is desirable in some situations, but maybe another function to initialize a "default" global object makes sense as well?
I added tests for all the cases that seemed notable, things like variables being defined/undefined in old/new global, and checking references to the old global in the new global scope. I also included a test for the original Proxy example to make sure it worked as expected.

Add Runtime.SetGlobalObject() method.
